#!/bin/bash -e

# display usage

usage()
{
    echo "Usage:"
    echo "  ./run [options] [environment]"
    echo
    echo "options:"
    echo "  server     run flask server"
    echo "  build      generate static files"
    echo
    echo "environment:"
    echo "  prod      (default) use environment variables from .env.prod"
    echo "  dev       use environment variables from .env.dev"
    echo
    echo "example:"
    echo "  ./run server dev"
    echo "  ./run build prod"
    echo "  ./run deploy"
}

. venv/bin/activate

# Select environment variables

ENV=".env.prod"
deploy_commit_message=""

if [ $2 ] && [ $2 == "dev" ]; then
    ENV=".env.dev"
fi

# run commands

runserver () {
    echo "Running flask server in $ENV environment"
    echo "Environment variables:"
    cat $ENV
    source $ENV && python app.py
}

build () {
    echo "Generating static pages in $ENV environment"
    echo "Environment variables:"
    cat $ENV
    source $ENV && python freeze.py
}

deploy () {
    echo "Deploying static site on github pages"
    cp -r build/* ../ancientknowledgewebsite/
    cd ../ancientknowledgewebsite/
    git add .
    git commit -m "$deploy_commit_message"
    git push origin master
}

if [ "$1" == "server" ]; then
    runserver
elif [ "$1" == "build" ]; then
    build
elif [ "$1" == "deploy" ]; then
    read -p 'Deployment commit message: ' deploy_commit_message
    build
    deploy
else
    usage
    exit 1
fi
